### ISSUE TITLE
Include single yaml file?

### ISSUE THREAD

**Issue by t-ru** [SUSE-Enceladus/keg#88]
Hello,

I've a directory /data/repositories. In this directory are multiple yaml files.

/data/repositories/repo-1.yaml
/data/repositories/repo-2.yaml
/data/repositories/repo-3.yaml

I added a include:

```
profiles:
  common: 
    include:
      - repositories

```
This includes all yaml-files from /data/repositories. But I want to include not all files.

How can I ensure that only repo-1.yaml is included and repo-2.yaml,...  not?

Best regards
Thomas

**Comment by jgleissner** [comment]
You can't. Keg uses directories to implement hierarchies, and each directory is basically a unit. The option to have multiple files in one directory allows for splitting it into more manageable bits but for keg it doesn't matter.

**Comment by t-ru** [comment]
The option to have multiple files in a directory does not allow splitting into more manageable parts. It hinders it!

Why?

I've:

`/packages/sle-15-3.pattern-base.yaml`
This file contains all packages from pattern "pattern-base" I want to install

`/packages/sle-15-3.pattern-enhanced-base.yaml`
This file contains all packages from pattern "pattern-enhanced-base" I want to install

`/packages/sle-15-x.sap-note-2578899.packages-sles.yaml`
This file contains all packages I want to install if product is SLES.

`/packages/sle-15-x.sap-note-2578899.packages-sles4sap.yaml`
This file contains all packages I want to install if product is SLES4SAP.

I've many build types:

- 1: SLES with pattern-base, packages-sles
- 2: SLES4SAP with pattern-base, packages-sles4sap
- 3: SLES with pattern-base, pattern-enhanced-base, packages-sles
- 4: SLES with pattern-base, pattern-enhanced-base, packages-sles4sap

To implement this it results in a copy&paste nightmare:

/packages/type-1/sle-15-3.pattern-base.yaml
/packages/type-1/sle-15-3.packages-sles.yaml
/packages/type-2/sle-15-3.pattern-base.yaml
/packages/type-2/sle-15-3.packages-sles4sap.yaml
/packages/type-3/sle-15-3.pattern-base.yaml
/packages/type-3/sle-15-3.packages-sles.yaml
/packages/type-3/sle-15-3.pattern-enhanced-base.yaml
/packages/type-4/sle-15-3.pattern-base.yaml
/packages/type-4/sle-15-3.packages-sles4sap.yaml
/packages/type-4/sle-15-3.pattern-enhanced-base.yaml

This is the reason I ask for include of single file.

**Comment by jgleissner** [comment]
The `include` statement in the image definition does not include just one directory, but a tree. For instance, `include: - sles/enhanced` reads everything in `sles/` and then merges all keys from `sles/enhanced` into it. Keg uses directory hierarchy to implement inheritance. The idea is that you have general configuration bits in the upper levels and more specialized ones in the lower levels. One of the main design goals of keg was to avoid duplication as much as possible, although this depends in large parts on how you structure the data, as keg itself mandates little in terms of how you can lay out your data.

Image definitions can have additional `include-paths` configured, which create additional search trees under the given `include` dirs, which is intended to add version specific bits (but again keg doesn't force you to use it that way). For instance, if you have 

```yaml
include:
  - sles/enhanced`
 ```
 and
```yaml
include-paths:
  - 15/sp1
  - 15/sp2
 ```

you would end up with the following merge order:
```
sles
sles/15
sles/15/sp1
sles/15/sp2
sles/enhanced
sles/enhanced/15
sles/enhanced/15/sp1
sles/enhanced/15/sp2
```
The idea here is obviously to put SLES 15 specific bits into `sles/15`, SLES 15 "enhanced" ones into `sles/enhanced/15` and any SP specific adjustments into the `sp` sub-dirs. At least that is (approximately) how we use it in https://github.com/SUSE-Enceladus/keg-recipes. Structuring the data differently is possible and at the user's discretion. Including a single yaml file however doesn't fit into the overall design.

**Comment by t-ru** [comment]
Hello,

**image.yaml**

```
image:
  name: sle-15-3.vmware.sap-as
  displayname: sle 15.3 vmware sap-as
  specification: SUSE Linux Enterprise Server Image / SUSE Linux Enterprise Server for SAP Applications Image
  author: Thomas Rudolph
  contact: thomas(dot)rudolph(at)all-for-one(dot)com
  schemaversion: "7.3"
  version: 1.0.0
preferences:
  bootloader_theme: "SLE"
  bootsplash_theme: "SLE"
  packagemanager: "zypper"
  rpm_check_signatures: "false"
  rpm_excludedocs: "true"
#preferences:
#  include:
#    - preferences
```

Result:

```
[ INFO    ]: 16:02:36 | Using KIWI schema: suse-vm
{ 'archives': {},
  'generator': 'keg 1.1.0',
  'image': { 'author': 'Thomas Rudolph',
             'contact': 'thomas(dot)rudolph(at)all-for-one(dot)com',
             'displayname': 'sle 15.3 vmware sap-as',
             'name': 'sle-15-3.vmware.sap-as',
             'schemaversion': '7.3',
             'specification': 'SUSE Linux Enterprise Server Image / SUSE Linux '
                              'Enterprise Server for SAP Applications Image',
             'version': '1.0.0'},
  'image source path': 'sle-15-3.vmware.sap-as',
  'preferences': { 'bootloader_theme': 'SLE',
                   'bootsplash_theme': 'SLE',
                   'packagemanager': 'zypper',
                   'rpm_check_signatures': 'false',
                   'rpm_excludedocs': 'true'},
  'profiles': { 'common': {'description': 'Common Profile'},
                'sles-vmware': {'description': 'SLES VMware Guest Image'},
                'sles4sap-vmware': { 'description': 'SLES for SAP Applications '
                                                    'VMware Guest Image'}},
  'schema': 'suse-vm',
  'timestamp': '2022-02-22 15:02:36'}
```
okay.

**image.yaml**

```
image:
  name: sle-15-3.vmware.sap-as
  displayname: sle 15.3 vmware sap-as
  specification: SUSE Linux Enterprise Server Image / SUSE Linux Enterprise Server for SAP Applications Image
  author: Thomas Rudolph
  contact: thomas(dot)rudolph(at)all-for-one(dot)com
  schemaversion: "7.3"
  version: 1.0.0
#preferences:
#  bootloader_theme: "SLE"
#  bootsplash_theme: "SLE"
#  packagemanager: "zypper"
#  rpm_check_signatures: "false"
#  rpm_excludedocs: "true"
preferences:
  include:
    - preferences
```
Result:

```
[ INFO    ]: 16:05:14 | Using KIWI schema: suse-vm
{ 'archives': {},
  'generator': 'keg 1.1.0',
  'image': { 'author': 'Thomas Rudolph',
             'contact': 'thomas(dot)rudolph(at)all-for-one(dot)com',
             'displayname': 'sle 15.3 vmware sap-as',
             'name': 'sle-15-3.vmware.sap-as',
             'schemaversion': '7.3',
             'specification': 'SUSE Linux Enterprise Server Image / SUSE Linux '
                              'Enterprise Server for SAP Applications Image',
             'version': '1.0.0'},
  'image source path': 'sle-15-3.vmware.sap-as',
  'preferences': {'include': ['preferences']},
  'profiles': { 'common': {'description': 'Common Profile'},
                'sles-vmware': {'description': 'SLES VMware Guest Image'},
                'sles4sap-vmware': { 'description': 'SLES for SAP Applications '
                                                    'VMware Guest Image'}},
  'schema': 'suse-vm',
  'timestamp': '2022-02-22 15:05:14'}
```
Not okay. Files located in data/preferences will not included.

What is wrong?

**Comment by jgleissner** [comment]
`preferences` is not a top level key. There are some hard-coded preference tags in the jinja template (see https://github.com/SUSE-Enceladus/keg-recipes/blob/develop/schemas/vm.kiwi.templ#L31). Would perhaps be nice to have those configurable at some point. You can use a custom template if course if you need to change those.

Everything else is configured in profiles. It makes a difference where they are included and whether there are profiles beyond `common`, as this determines whether they end up in the general `<preferences>` section or a profile specific one. For the `preferences` sections, the following keys are relevant:

```yaml
profile:  (this essentially maps to kiwi's '<type>' section)
    parameters:  (attributes for '<type>' tag)
        attribute: value
        kernelcmdline:  (special case, not simply a string but a dict)
            param: value  (gets appended as param=value to kernelcmdline string)
            ...
        ...
    bootloader:
        attribute: value
        ...
    size: value
    oemconfig:
        tag: value
        ...
    machine:
        attribute: value
        ...
preferences:
    tag: value (any non-'<type>' kiwi tag, only works in 'common' profile
```
`kernelcmdline` is a dict instead of a simple string, so it allows for composing it from different source via inheritance and overwriting. Not everything that can be configured in kiwi is supported by keg or the template in keg-recipes (which may be the more restricting factor actually). The idea was to simplify things a bit, but if there's anything missing I'm happy to look into it.

As stated above, the `preferences` section really only works in the `common` profile, although I think there's no reason to disallow it in other profiles. I'll look into adding it.

There is some documentation about this available here: https://documentation.suse.com/keg/1/single-html/keg/#recipes-basics (might be behind the version in the repo though). Documentation could be more verbose, admittedly, so any feedback on it is welcome.
